#!/bin/bash

case $1 in
start)
    # 重载trim_http_cgi服务，防止trim_app_cgi服务抢先注册
    # 验证服务是否存在
    if ! systemctl is-enabled --quiet trim_http_cgi.service; then
        echo "错误：服务 trim_http_cgi.service 不存在！"
        exit 1
    fi
    /usr/bin/systemctl restart trim_http_cgi.service
    exit 0
    ;;
stop)
    exit 0
    ;;
status)
    exit 0
    ;;
log)
    exit 0
    ;;
*)
    exit 1
    ;;
esac